#雅思站的增量更新
sh run.sh yasi_xiaozhan_inc
sh del_res.sh yasi_xiaozhan_inc
sh run.sh youshengxiao_ysxiao_zixun_inc
sh del_res.sh youshengxiao_ysxiao_zixun_inc
sh run.sh yasi_taisha_inc
sh del_res.sh yasi_taisha_inc
sh run.sh youshengxiao_ysxiao_zhongdianxiaoxue
sh del_res.sh youshengxiao_ysxiao_zhongdianxiaoxue
sh run.sh inc_16_guitarworld
sh del_res.sh inc_16_guitarworld
sh run.sh toefl_keke_jijing_inc
sh del_res.sh toefl_keke_jijing_inc
sh run.sh toefl_taisha_inc
sh del_res.sh toefl_taisha_inc
sh run.sh gre_tiandao_inc
sh del_res.sh gre_tiandao_inc
sh run.sh gmat_tiandao_inc
sh del_res.sh gmat_tiandao_inc
sh run.sh sat_zhan_inc
sh del_res.sh sat_zhan_inc
sh run.sh gmat_zhan_inc
sh del_res.sh gmat_zhan_inc
sh run.sh gre_xiaozhan_inc
sh del_res.sh gre_xiaozhan_inc
sh run.sh toefl_xiaozhan_inc
sh del_res.sh toefl_xiaozhan_inc
sh run.sh kaoyan_chinakaoyan_inc
sh del_res.sh kaoyan_chinakaoyan_inc
sh run.sh kaoyan_kaoyan_inc
sh del_res.sh kaoyan_kaoyan_inc
sh run.sh kaoyan_eol_inc
sh del_res.sh kaoyan_eol_inc
sh run.sh gaokao_news_gaokao
sh del_res.sh gaokao_news_gaokao
#sh run.sh gaokao_news_liuxue86
#sh del_res.sh gaokao_news_liuxue86
sh run.sh gaokao_eol
sh del_res.sh gaokao_eol
sh run.sh qiuzhi_zhaopin
sh del_res.sh qiuzhi_zhaopin
sh run.sh qiuzhi_shixisheng
sh del_res.sh qiuzhi_shixisheng
sh run.sh gangqin_new_163_inc
sh del_res.sh gangqin_new_163_inc
sh run.sh cet46_inc
sh del_res.sh cet46_inc
sh run.sh toefl_xdf_inc
sh del_res.sh toefl_xdf_inc
sh run.sh inc_10_youku
sh del_res.sh inc_10_youku
sh run.sh inc_gangqin_youku_6
sh del_res.sh inc_gangqin_youku_6
sh run.sh sheying_xingshe
sh del_res.sh sheying_xingshe
sh run.sh sheying_heiguangwang
sh del_res.sh sheying_heiguangwang
sh run.sh sheying_fsbus
sh del_res.sh sheying_fsbus
sh run.sh kaoyan_kuakao
sh del_res.sh kaoyan_kuakao
sh run.sh kaoyan_chsi
sh del_res.sh kaoyan_chsi
sh run.sh kaoyan_yuloo
sh del_res.sh kaoyan_yuloo
sh run.sh dota_guanwang_news
sh del_res.sh dota_guanwang_news
sh run.sh dota_tgbus_news
sh del_res.sh dota_tgbus_news
sh run.sh dota_replays_news
sh del_res.sh dota_replays_news
sh run.sh kaoyan_kaoshidian
sh del_res.sh kaoyan_kaoshidian
sh run.sh jinrong_xinlang_inc
sh del_res.sh jinrong_xinlang_inc
sh run.sh jinrong_chinaacc_inc
sh del_res.sh jinrong_chinaacc_inc
sh run.sh acca_accazhongguo
sh del_res.sh acca_accazhongguo
sh run.sh 51job_shixisheng
sh del_res.sh 51job_shixisheng
sh run.sh qiuzhi_shixisheng_shixisheng
sh del_res.sh qiuzhi_shixisheng_shixisheng
sh run.sh chengxuyuan_boke_inc 
sh del_res.sh chengxuyuan_boke_inc
sh run.sh kaoyan_cnky_inc
sh del_res.sh kaoyan_cnky_inc
sh run.sh zhongkaocom_inc
sh del_res.sh zhongkaocom_inc
sh run.sh zhongkaosina_inc
sh del_res.sh zhongkaosina_inc
sh run.sh zhongkaoxdfcn_inc
sh del_res.sh zhongkaoxdfcn_inc
sh run.sh 233kuaiji
sh del_res.sh 233kuaiji
sh run.sh eoffcn_gongwuyuan_inc
sh del_res.sh eoffcn_gongwuyuan_inc
sh run.sh 233jzs_inc
sh del_res.sh 233jzs_inc
sh run.sh qiuzhi_jianliwang
sh del_res.sh qiuzhi_jianliwang
sh run.sh dongman_qiongkong
sh del_res.sh dongman_qiongkong
sh run.sh dongman_missevan
sh del_res.sh dongman_missevan
sh run.sh yixue_zhengbao_inc
sh del_res.sh yixue_zhengbao_inc
sh run.sh kuaiji_dongaokuaiji_inc
sh del_res.sh kuaiji_dongaokuaiji_inc
sh run.sh kuaiji_zhengbao_inc
sh del_res.sh kuaiji_zhengbao_inc
sh run.sh jingyan_sohu_gaokao_inc
sh del_res.sh jingyan_sohu_gaokao_inc
sh run.sh jingyan_sohu_liuxue_inc
sh del_res.sh jingyan_sohu_liuxue_inc
sh run.sh kztk_qnr_inc
sh del_res.sh kztk_qnr_inc
sh run.sh wenda_cxy_bky_inc
sh del_res.sh wenda_cxy_bky_inc
sh run.sh 51sxue_xiaoxue_youshengxiao
sh del_res.sh 51sxue_xiaoxue_youshengxiao
sh run.sh chinadance_inc
sh del_res.sh chinadance_inc
sh run.sh xingzuo123_inc
sh del_res.sh xingzuo123_inc
sh run.sh xmswim_inc
sh del_res.sh xmswim_inc
sh run.sh hujiang_deyu_inc
sh del_res.sh hujiang_deyu_inc
sh run.sh hujiang_riyu_inc
sh del_res.sh hujiang_riyu_inc
sh run.sh gu_inc
sh del_res.sh gu_inc
sh run.sh shufa_inc
sh del_res.sh shufa_inc
sh run.sh jingyan_xuexila_inc
sh del_res.sh jingyan_xuexila_inc
sh run.sh wenda_cxy_segmentfault_inc
sh del_res.sh wenda_cxy_segmentfault_inc
sh run.sh wenda_tgnet_inc
sh del_res.sh wenda_tgnet_inc
sh run.sh wenda_baixing_inc
sh del_res.sh wenda_baixing_inc
sh run.sh zuowen_zgxcc_inc
sh del_res.sh zuowen_zgxcc_inc
sh run.sh jingyan_120ask_inc
sh del_res.sh jingyan_120ask_inc
sh run.sh cxy_ithome_inc
sh del_res.sh cxy_ithome_inc
sh run.sh english_yingyu_inc 
sh del_res.sh english_yingyu_inc
sh run.sh dianzishangwu_ebrun_inc
sh del_res.sh dianzishangwu_ebrun_inc
sh run.sh dianzishangwu_exam8_inc
sh del_res.sh dianzishangwu_exam8_inc
sh run.sh guoxue_guoxue_inc
sh del_res.sh guoxue_guoxue_inc
sh run.sh yujia_yujia_inc
sh del_res.sh yujia_yujia_inc
sh run.sh yujia_jianfei_inc
sh del_res.sh yujia_jianfei_inc
sh run.sh huihua_woaihuahua_inc
sh del_res.sh huihua_woaihuahua_inc
sh run.sh wushu_wushu_inc
sh del_res.sh wushu_wushu_inc
sh run.sh shufa_sfrx_inc
sh del_res.sh shufa_sfrx_inc
sh run.sh act_bailiedu_inc
sh del_res.sh act_bailiedu_inc
sh run.sh act_xiaoma_inc
sh del_res.sh act_xiaoma_inc
sh run.sh deyu_tingroom_inc
sh del_res.sh deyu_tingroom_inc
sh run.sh licai_hexun_inc
sh del_res.sh licai_hexun_inc
sh run.sh licai_rong360_inc
sh del_res.sh licai_rong360_inc
sh run.sh licai_sina_inc
sh del_res.sh licai_sina_inc
sh run.sh licai_zhongjin_inc
sh del_res.sh licai_zhongjin_inc
sh run.sh changge_52jinshan_inc
sh del_res.sh changge_52jinshan_inc
sh run.sh putonghua_wangxiao_inc
sh del_res.sh putonghua_wangxiao_inc
sh run.sh putonghua_exam8_inc
sh del_res.sh putonghua_exam8_inc
sh run.sh youyong_pclady_inc
sh del_res.sh youyong_pclady_inc
sh run.sh pingpang_sohu_inc
sh del_res.sh pingpang_sohu_inc
sh run.sh sheji_cndesign_inc
sh del_res.sh sheji_cndesign_inc
sh run.sh sheji_shejinet_inc
sh del_res.sh sheji_shejinet_inc
sh run.sh sheji_uggd_inc
sh del_res.sh sheji_uggd_inc
sh run.sh sheji_ui001_inc 
sh del_res.sh sheji_ui001_inc
sh run.sh xiaoxue_233_inc
sh del_res.sh xiaoxue_233_inc
sh run.sh linux_idc
sh del_res.sh linux_idc
sh run.sh xiaoxue_51edu_inc
sh del_res.sh xiaoxue_51edu_inc
sh run.sh magic_magicyou_inc
sh del_res.sh magic_magicyou_inc
sh run.sh mba_mbachina_inc
sh del_res.sh mba_mbachina_inc
sh run.sh mba_wangxiao_inc
sh del_res.sh mba_wangxiao_inc
sh run.sh zhuanshengben_exam8_inc
sh del_res.sh zhuanshengben_exam8_inc
sh run.sh aoshu_juren_inc
sh del_res.sh aoshu_juren_inc
sh run.sh yingyangshi_kaoshi110_inc
sh del_res.sh yingyangshi_kaoshi110_inc
sh run.sh yingyangshi_wangxiao_inc 
sh del_res.sh yingyangshi_wangxiao_inc
sh run.sh yishi_exam8_inc
sh del_res.sh yishi_exam8_inc
sh run.sh yishi_med66_inc
sh del_res.sh yishi_med66_inc
sh run.sh yishi_wangxiao_inc
sh del_res.sh yishi_wangxiao_inc
sh run.sh korean_hujiang_inc
sh del_res.sh korean_hujiang_inc
sh run.sh spanish_hujiang_inc
sh del_res.sh spanish_hujiang_inc
sh run.sh spanish_tingroom_inc
sh del_res.sh spanish_tingroom_inc
sh run.sh korean_tingroom_inc
sh del_res.sh korean_tingroom_inc
